name: toku
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  just_audio: ^0.9.36
  audio_service: ^0.18.10
  audio_session: ^0.1.11
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image_page/
    - assets/images/colors/
    - assets/images/family_members/
    - assets/images/numbers/
    - assets/sounds/colors/
    - assets/sounds/family_members/
    - assets/sounds/numbers/
